import { IAddCardFieldProps } from "../src/interfaces/index";

const inputs: IAddCardFieldProps[] = [
    {
        _id: "1",
        label: "Name",
        placeholder: "Enter Name",
        templateId: "1",
        order: 1,
        key: "name",
        type: "front",
    },
    {
        _id: "2",
        label: "Name",
        placeholder: "Enter Name",
        templateId: "2",
        order: 1,
        key: "name",
        type: "front",
    },
    {
        _id: "3",
        label: "Name",
        placeholder: "Enter Name",
        templateId: "3",
        order: 1,
        key: "name",
        type: "front",
    },
    {
        _id: "4",
        label: "Name",
        placeholder: "Enter Name",
        templateId: "4",
        order: 1,
        key: "name",
        type: "front",
    },
    {
        _id: "5",
        label: "Name",
        placeholder: "Enter Name",
        templateId: "5",
        order: 1,
        key: "name",
        type: "front",
    },
    {
        _id: "6",
        label: "Name",
        placeholder: "Enter Name",
        templateId: "6",
        order: 1,
        key: "name",
        type: "front",
    },
    {
        _id: "7",
        label: "Name",
        placeholder: "Enter Name",
        templateId: "7",
        order: 1,
        key: "name",
        type: "front",
    },
    {
        _id: "8",
        label: "Name",
        placeholder: "Enter Name",
        templateId: "8",
        order: 1,
        key: "name",
        type: "front",
    },
    {
        _id: "9",
        label: "Name",
        placeholder: "Enter Name",
        templateId: "9",
        order: 1,
        key: "name",
        type: "front",
    },
    {
        _id: "10",
        label: "Phone Number",
        placeholder: "Enter Phone Number",
        templateId: "1",
        order: 2,
        key: "phoneNumber",
        type: "front",
    },
    {
        _id: "11",
        label: "Phone Number",
        placeholder: "Enter Phone Number",
        templateId: "2",
        order: 2,
        key: "phoneNumber",
        type: "front",
    },
    {
        _id: "12",
        label: "Phone Number",
        placeholder: "Enter Phone Number",
        templateId: "3",
        order: 2,
        key: "phoneNumber",
        type: "front",
    },
    {
        _id: "13",
        label: "Phone Number",
        placeholder: "Enter Phone Number",
        templateId: "4",
        order: 2,
        key: "phoneNumber",
        type: "front",
    },
    {
        _id: "14",
        label: "Phone Number",
        placeholder: "Enter Phone Number",
        templateId: "5",
        order: 2,
        key: "phoneNumber",
        type: "front",
    },
    {
        _id: "15",
        label: "Phone Number",
        placeholder: "Enter Phone Number",
        templateId: "6",
        order: 2,
        key: "phoneNumber",
        type: "front",
    },
    {
        _id: "16",
        label: "Phone Number",
        placeholder: "Enter Phone Number",
        templateId: "7",
        order: 2,
        key: "phoneNumber",
        type: "front",
    },
    {
        _id: "17",
        label: "Phone Number",
        placeholder: "Enter Phone Number",
        templateId: "8",
        order: 2,
        key: "phoneNumber",
        type: "front",
    },
    {
        _id: "18",
        label: "Phone Number",
        placeholder: "Enter Phone Number",
        templateId: "9",
        order: 2,
        key: "phoneNumber",
        type: "front",
    },
    {
        _id: "19",
        label: "Email Address",
        placeholder: "Enter Email Address",
        templateId: "1",
        order: 3,
        key: "emailAddress",
        type: "front",
    },
    {
        _id: "20",
        label: "Email Address",
        placeholder: "Enter Email Address",
        templateId: "2",
        order: 3,
        key: "emailAddress",
        type: "front",
    },
    {
        _id: "21",
        label: "Email Address",
        placeholder: "Enter Email Address",
        templateId: "3",
        order: 3,
        key: "emailAddress",
        type: "front",
    },
    {
        _id: "22",
        label: "Email Address",
        placeholder: "Enter Email Address",
        templateId: "4",
        order: 3,
        key: "emailAddress",
        type: "front",
    },
    {
        _id: "23",
        label: "Email Address",
        placeholder: "Enter Email Address",
        templateId: "5",
        order: 3,
        key: "emailAddress",
        type: "front",
    },
    {
        _id: "24",
        label: "Email Address",
        placeholder: "Enter Email Address",
        templateId: "6",
        order: 3,
        key: "emailAddress",
        type: "front",
    },
    {
        _id: "25",
        label: "Email Address",
        placeholder: "Enter Email Address",
        templateId: "7",
        order: 3,
        key: "emailAddress",
        type: "front",
    },
    {
        _id: "26",
        label: "Email Address",
        placeholder: "Enter Email Address",
        templateId: "8",
        order: 3,
        key: "emailAddress",
        type: "front",
    },
    {
        _id: "27",
        label: "Email Address",
        placeholder: "Enter Email Address",
        templateId: "9",
        order: 3,
        key: "emailAddress",
        type: "front",
    },
    {
        _id: "28",
        label: "Enter Company",
        placeholder: "Enter Company",
        templateId: "1",
        order: 4,
        key: "company",
        type: "back",
    },
    {
        _id: "29",
        label: "Enter Company",
        placeholder: "Enter Company",
        templateId: "2",
        order: 4,
        key: "company",
        type: "back",
    },
    {
        _id: "30",
        label: "Enter Company",
        placeholder: "Enter Company",
        templateId: "3",
        order: 4,
        key: "company",
        type: "back",
    },
    {
        _id: "31",
        label: "Enter Company",
        placeholder: "Enter Company",
        templateId: "4",
        order: 4,
        key: "company",
        type: "back",
    },
    {
        _id: "32",
        label: "Enter Company",
        placeholder: "Enter Company",
        templateId: "5",
        order: 4,
        key: "company",
        type: "back",
    },
    {
        _id: "33",
        label: "Enter Company",
        placeholder: "Enter Company",
        templateId: "6",
        order: 4,
        key: "company",
        type: "back",
    },
    {
        _id: "34",
        label: "Enter Company",
        placeholder: "Enter Company",
        templateId: "7",
        order: 4,
        key: "company",
        type: "back",
    },
    {
        _id: "35",
        label: "Enter Company",
        placeholder: "Enter Company",
        templateId: "8",
        order: 4,
        key: "company",
        type: "back",
    },
    {
        _id: "36",
        label: "Enter Company",
        placeholder: "Enter Company",
        templateId: "9",
        order: 4,
        key: "company",
        type: "back",
    },
    {
        _id: "37",
        label: "Website",
        placeholder: "Enter Website",
        templateId: "1",
        order: 4,
        key: "website",
        type: "back",
    },
    {
        _id: "38",
        label: "Website",
        placeholder: "Enter Website",
        templateId: "2",
        order: 4,
        key: "website",
        type: "back",
    },
    {
        _id: "39",
        label: "Website",
        placeholder: "Enter Website",
        templateId: "3",
        order: 4,
        key: "website",
        type: "back",
    },
    {
        _id: "40",
        label: "Website",
        placeholder: "Enter Website",
        templateId: "4",
        order: 4,
        key: "website",
        type: "back",
    },
    {
        _id: "41",
        label: "Website",
        placeholder: "Enter Website",
        templateId: "5",
        order: 4,
        key: "website",
        type: "back",
    },
    {
        _id: "42",
        label: "Website",
        placeholder: "Enter Website",
        templateId: "6",
        order: 4,
        key: "website",
        type: "back",
    },
    {
        _id: "43",
        label: "Website",
        placeholder: "Enter Website",
        templateId: "7",
        order: 4,
        key: "website",
        type: "back",
    },
    {
        _id: "44",
        label: "Website",
        placeholder: "Enter Website",
        templateId: "8",
        order: 4,
        key: "website",
        type: "back",
    },
    {
        _id: "45",
        label: "Website",
        placeholder: "Enter Website",
        templateId: "9",
        order: 4,
        key: "website",
        type: "back",
    },
    {
        _id: "46",
        label: "Facebook",
        placeholder: "Enter Facebbok",
        templateId: "1",
        key: "facebook",
        order: 4,
        type: "back",
    },
    {
        _id: "47",
        label: "Facebook",
        placeholder: "Enter Facebbok",
        templateId: "2",
        key: "facebook",
        order: 4,
        type: "back",
    },
    {
        _id: "48",
        label: "Facebook",
        placeholder: "Enter Facebbok",
        templateId: "3",
        key: "facebook",
        order: 4,
        type: "back",
    },
    {
        _id: "49",
        label: "Facebook",
        placeholder: "Enter Facebbok",
        templateId: "4",
        key: "facebook",
        order: 4,
        type: "back",
    },
    {
        _id: "50",
        label: "Facebook",
        placeholder: "Enter Facebbok",
        templateId: "5",
        key: "facebook",
        order: 4,
        type: "back",
    },
    {
        _id: "51",
        label: "Facebook",
        placeholder: "Enter Facebbok",
        templateId: "6",
        key: "facebook",
        order: 4,
        type: "back",
    },
    {
        _id: "52",
        label: "Facebook",
        placeholder: "Enter Facebbok",
        templateId: "7",
        key: "facebook",
        order: 4,
        type: "back",
    },
    {
        _id: "53",
        label: "Facebook",
        placeholder: "Enter Facebbok",
        templateId: "8",
        key: "facebook",
        order: 4,
        type: "back",
    },
    {
        _id: "54",
        label: "Facebook",
        placeholder: "Enter Facebbok",
        templateId: "9",
        key: "facebook",
        order: 4,
        type: "back",
    },
];

export const filterTemplatesById = (templateId: string | number) => {
    return inputs
        .filter((input) => input.templateId === templateId)
        .sort((a, b) => a?.order - b?.order);
};

export default inputs;
